(broken) Upgrade Jekyll without changing core configuration (except for 'safe')
Expectations:

- Adding `safe: false` will obviate having to carry that symlink patch on Jekyll.
- This shouldn't break anything.
- A diff of the output directories shouldn't be substantially different.

Results:

- I was right about `safe: false` and the now-unnecessary patch. Woo!
- Activerecord 4.x blows up on Ruby 1.8.7 and won't install. (This affected the
  master branch as well, if you tried to do bundle update after Rails 4 came
  out. I fixed it on master instead of fixing it on this branch.)
- Our jekyll command in `rake generate` no longer works.
- The format of the `include` option changed, and now issues a deprecation warning.
- The pygments cache plugin is entirely broken, and the site will not generate
  without removing it. (However, the improved pygments pipe handling means this
  only adds 10-15s to the total build time.)
- The sitemap is broken: it now has two full copies of the directory for every page.
  (http://docs.puppetlabs.com/pe/3.0/puppet_overview.html becomes
  http://docs.puppetlabs.com/pe/3.0/pe/3.0/puppet_overview.html)
- When running stock Jekyll 1.1.2, compilation may explode when encountering any
  <name@domain.com> email address links in the site, with a Kramdown error like
  the following:

  Generating...   Conversion error: There was an error converting
  'mcollective/deploy/middleware/activemq.md'.

  /Users/nick/Documents/puppet-docs/vendor/bundle/ruby/1.8/gems/kramdown-1.0.2/lib/kramdown/converter/html.rb:404:in
  `obfuscate': undefined method `encoding' for "mailto":String (NoMethodError)

  I tracked this down: lib/jekyll/core_ext.rb was ill-advisedly adding a bogus
  method to String. I fixed it and submitted a pull request to upstream as
  9ca7f70d70c612e3d590f009bcb9ae64a6aedd78, and cherry-picked it into our Puppet
  Labs-specific branch as 73f344028681d907ccd8e570db21b15ed3d4fa58. My pull was
  accepted, so hopefully we should be fine with stock Jekyll once 1.1.3 comes out.
- Pygments highlighting for Ruby now farts on Namespace::Namespace
  identifiers. This is a bug in Pygments 1.6, which is vendored by pygments.rb. (I
  had been generating the site with 1.5, dunno what Fred has been generating it
  with. The bug is fixed in prerelease builds of Pygments 1.7, so I guess it will
  eventually get fixed if we keep running bundle update from time to time.)
- The Puppet lexer was added to Pygments as of version 1.6! So we should be
  able to highlight Puppet code for real now instead of settling for Ruby.