(fine) Update sitemap generator plugin to e5c55f017 (from its source repo)
https://github.com/kinnetica/jekyll-plugins/blob/master/sitemap_generator.rb

The current commit, at master, is 9ec603a, but it doesn't work with Jekyll 2.x;
they made an incompatible change to support 3.x. Results in an error like:

jekyll 2.5.3 | Error:  undefined method `docs' for nil:NilClass

We can update to that commit later, once our Jekyll has caught up.